import type { Metadata } from "next";
import { Playfair_Display, Inter } from "next/font/google";
import "./globals.css";
import { databases } from "@/lib/appwrite";


const playfair = Playfair_Display({
  subsets: ["latin"],
});

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) 


{
  return (
    <html lang="en" className="light ">
      <body className={`${inter.className} bg-[#E6E6FA] dark:text-black`}>
        {children}
      </body>
      
    </html>
  );
}